# Site settings
title: CPearson.me.uk
email: chris@cpearson.me.uk
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Chris Pearson.  Developer, father & nerd.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cpearson.me.uk" # the base hostname & protocol for your site
author: Chris Pearson
permalink: /:year/:month/:day/:title/

paginate: 10
paginate_path: "/page:num/"

# Build settings
markdown: kramdown

defaults:
    -
      scope:
        path: ""
      values:
        author: "Chris Pearson"
        layout: post
